sudo: required
language: cpp
compiler:
  - gcc
only:
  - master
  - devel
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DFAS_BUILD_ALL=ON -DFAS_ENABLE_ALL_WARNING=ON ..
  - cmake --build .
  - ctest --output-on-failure
  - cd ..
  - ./.ci/cppcheck.sh
 
